### ISSUE TITLE
How can i change STRUCT_ITEM cValue?

### ISSUE THREAD

**Issue by mady888** [seitbnao/WYDGlobal_W2ppPatch#1]
the STRUCT_ITEM cValue 's type is unsigned char which max length is 255, but i want to change it to 500. when i modify the type of cValue from unsigned char to int, the client will be wrong, pls help me, thanks.

**Comment by seitbnao** [comment]
unfortunately, it is the current structure of the game, it is up to the developer to increase the size of the structure to higher values
